### ISSUE TITLE
Estimating mean sd when median iqr is negative

### ISSUE THREAD

**Issue by mrozga** [stmcg/estmeansd-ShinyApp#1]
Hello, On the estmeansd ShinyApp and on R, when I enter negative values for the median and variance, I get "NA" or "error". What is the appropriate way to estimate mean and SD when median and IQR are negative?

**Comment by stmcg** [comment]
Hi,

Thanks for posting. The BC and MLN methods in estmeansd make certain assumptions on the underlying distribution of the data that require the data to be positive. This is why you are getting error messages when supplying negative data. One approach that I've used in this context is to (1) add a constant to the sample quantiles in order for them to be positive, (2) apply the package to the shifted data to estimate the mean and standard deviation, (3) subtract that constant from the estimated mean. 

There are also other methods in the literature for estimating the mean and standard deviation that make other assumptions (eg, that the outcome is normally distributed), which don't require data to be positive. A summary of these methods and their implementation in R is discussed here: https://arxiv.org/pdf/2302.14243.pdf

Best,
Sean

**Comment by mrozga** [comment]
Hi Sean,

Thank you for your response. This is extremely helpful!!

Best,
Mary

**Comment by stmcg** [comment]
Glad to hear!
